### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\ufe0f' in position 15: illegal multibyte sequence

### ISSUE THREAD

**Issue by lxingh** [Trung0246/ComfyUI-0246#26]
Traceback (most recent call last):
File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\__init__.py", line 1, in <module>
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 3205, in <module>
print("\033[95m" + lib0246.HEAD_LOG + "Loaded all nodes and apis." + "\033[0m")
UnicodeEncodeError: 'gbk' codec can't encode character '\ufe0f' in position 15: illegal multibyte sequence
Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246 module for custom nodes: 'gbk' codec can't encode character '\ufe0f' in position 15: illegal multibyte sequence

**Comment by Trung0246** [comment]
Uh what terminal you're using? Can you force the terminal you're using to unicode?
