### ISSUE TITLE
Comfyui latest update: AttributeError: 'NoneType' object has no attribute 'get_input_info'

### ISSUE THREAD

**Issue by bananasss00** [Trung0246/ComfyUI-0246#38]
```
Traceback (most recent call last):
  File "V:\comfyu_py311\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-0246\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 1071, in <module>
    lib0246.hijack(comfy_graph, "get_input_info", get_input_info_param_handle, get_input_info_res_handle)
  File "V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 373, in hijack
    old_func = getattr(scope, name)
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_input_info'
```

**Comment by Danamir** [comment]
Can confirm, I got the same bug with ComfyUI: `2546[bfc214](2024-08-15)`.

**Comment by BlackVortexAI** [comment]
Same her with version bfc214

**Comment by Trung0246** [comment]
Hm looks like the topological execution changed something. I'll take a look tomorrow.

**Comment by Trung0246** [comment]
Initial quick fix has been done. Did not test it yet for actual breakage since it's 1:00am here.

**Comment by BlackVortexAI** [comment]
Working THX

**Comment by Danamir** [comment]
>  Plus I was on vacation for last 2 weeks so I did not heard about the news it being merged.

No worries, thanks for the quick fix ! 😅

**Comment by zhenyuanzhou** [comment]
Same here

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 1090, in <module>
    lib0246.hijack(comfy_graph, "get_input_info", get_input_info_param_handle, get_input_info_res_handle)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 345, in hijack
    old_func = getattr(scope, name)
               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_input_info'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246 module for custom nodes: 'NoneType' object has no attribute 'get_input_info'

**Comment by subspecs** [comment]
This appears again, with the most recent version, same error and all.

**Comment by subspecs** [comment]
For now, I fixed it likes this for anyone wondering:

	old_func = getattr(scope, name, None)
	if old_func is None:
		return
